feat: add basic error handling and checks
Ensures:
- shell is Bash
- minimum Bash version is 3.2+
- logging format
- prevents sourcing to avoid overridden built-ins
- main function returns correct errors from sub-routines

diff --git a/bin/dotfiles b/bin/dotfiles
--- a/bin/dotfiles
+++ b/bin/dotfiles
@@ -12,10 +12,58 @@
 #       different files for Linux and macOS and does not support other
 #       deployment methods like subrepositories, git bare, or copying.
 #       Also does not support error handling for GNU Stow.
-function dotfiles::deploy {
+
+die() {
+    printf 'error: %s\n' "$@" 1>&2
+    exit 1
+}
+
+# Fail fast checks.
+# shellcheck disable=SC2292
+if [ -z "${BASH_VERSION:-}" ]; then
+    die 'Bash is required to interpret the script.'
+elif [[ -n "${POSIXLY_CORRECT+1}" ]]; then
+    die 'Script must not run in POSIX mode. Please unset POSIXLY_CORRECT.'
+fi
+
+# Prevent script form being sourced to avoid function or builtin overrides.
+(return 0 2>/dev/null) && die "dotfiles script cannot be sourced."
+
+# Require minimum Bash version and "$HOME" environment variable to be set.
+if [[ "${BASH_VERSINFO[0]}" -lt 3 ||
+    ("${BASH_VERSINFO[0]}" -eq 3 &&
+    "${BASH_VERSINFO[1]}" -lt 2) ]]; then
+    die "Bash version 3.2+ is required, exiting."
+elif [[ -z "${HOME:-}" ]]; then
+    die "'\$HOME' directory is unset, exiting."
+fi
+
+function log::error() {
+    printf 'dotfiles: %s: error: %s\n' "${FUNCNAME[1]}" "$*" 1>&2
+}
+
+function dotfiles::main() {
+    # Parse arguments.
+    if [[ "$#" -gt 0 ]]; then
+        case "$1" in
+            deploy)
+                dotfiles::deploy
+                ;;
+            *)
+                log::error "unrecognized command: '$1'"
+                return 1
+                ;;
+        esac
+    else
+        log::error "no arguments provided"
+        return 1
+    fi
+}
+
+function dotfiles::deploy() {
     if ! builtin command -v -- stow > /dev/null 2>&1; then
-        printf 'error: dotfiles requires GNU Stow for deployment, exiting\n'
-        exit 1
+        log::error "dotfiles requires GNU Stow for deployment, exiting"
+        return 1
     fi
 
     case "$OSTYPE" in
@@ -37,23 +85,9 @@ function dotfiles::deploy {
                  --ignore='.config/emacs'
             ;;
         *)
-            printf 'error: unrecognized operating system: %s\n' "$OSTYPE"
-            exit 1
+            log::error "unrecognized operating system: $OSTYPE"
+            return 1
     esac
 }
 
-# NOTE: only supports single arguments with basic errors and no usage string.
-if [[ "$#" -gt 0 ]]; then
-    case "$1" in
-        deploy)
-            dotfiles::deploy
-            ;;
-        *)
-            printf 'error: unrecognized command: %s\n' "$1"
-            exit 1
-            ;;
-    esac
-else
-    printf 'error: no arguments specified\n'
-    exit 1
-fi
+dotfiles::main "$@"; exit "$?"
